version: 2
updates:
  # Check for updates to npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "05:00"
      timezone: "UTC"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels: ["dependencies"]
    reviewers: ["pierrevensy"]
    assignees: ["pierrevensy"]
    groups:
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Check for updates to GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "chore(actions)"
      include: "scope"
    labels: ["github-actions"]
    reviewers: ["pierrevensy"]
    assignees: ["pierrevensy"]
    groups:
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"